# Ordering table descendaly according to MSH2 hotspot variants
custom_plot_config:
  targeted_MSH2:
    defaultsort:
      - column: "MSH2_c.942+3A>T"
        direction: desc
      - column: "MSH2_c.942+2T>A"
        direction: desc
      - column: "MSH2_c.942+2T>G"
        direction: desc
      - column: "MSH2_c.942+2T>C"
        direction: desc

# Defining threshold for MSH2 hotspot variants need for Sanger sequencing
targeted_MSH2_config:
  sanger_threshold : 20

# Assigning modules to run
run_modules:
  - targeted_MSH2
  
# Assigning template
template: "cmgg"